### PR TITLE
[WIP] Cross build using sbt 0.13.16

### PR DESCRIPTION
**Pull request by jonas**
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lightbend.paradox#sbt-paradox;0.2.12: not found
[warn] 	:: org.planet42#laika-sbt;0.6.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

### CODE REVIEW

**Comment by larsrh** [comment]
Recursive dependencies:

* [ ] sbt-paradox (lightbend/paradox#132)
  * [ ] sbt-web
* [ ] laika-sbt

**Comment by xuwei-k** [comment]
I just sent another pull request https://github.com/sbt/sbt-site/pull/107.

**Comment by larsrh** [comment]
@xuwei-k I guess this one can be closed, then.

**Comment by jonas** [comment]
Yes, superseded by #107

**Pull request closed without merging**
