### PR TITLE
update library dependencies

### PR DESCRIPTION
**Pull request by fgrutsch**
ran into a similar problem as mentioned in #172, except that scala-xml was the problem (also when using this plugin with sbt-native-packager).

also updated other dependencies as well

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @fgrutsch,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by ennru** [comment]
Hi @fgrutsch,
I just merged CI with GH workflows. Would be great if you can rebase this and help out with more modernisation.

**Comment by ennru** [comment]
Parts of this went into #188

**Comment by ennru** [comment]
All this is covered since #201, just a different hack around Scala XML.

**Pull request closed without merging**
