### PR TITLE
Gitbook support

### PR DESCRIPTION
**Pull request by jonas**
Resubmitted #62 to update the PR base branch.

This adds another site generator. To facilitate building documentation via CI there's a special option to install a local GitBook version for building the site.

### CODE REVIEW

**Comment by jonas** [comment]
@metasim Not sure how to fix the build. It looks like 395ff140a4595f45e04d10e7ac639fdde6691479 needs to be merged into the 1.0.0-RC2 branch.

**Comment by jonas** [comment]
I am also wondering if the migration notes should contain instructions for dealing with missing `site.addMappingsToSiteDir` which is the suggested way to use `sbt-unidoc`. I can add something like the following as a separate commit if you think it is useful:

```diff
diff --git a/notes/migrate-0.8.2-to-1.0.md b/notes/migrate-0.8.2-to-1.0.md
index 73b7482..d8a6042 100644
--- a/notes/migrate-0.8.2-to-1.0.md
+++ b/notes/migrate-0.8.2-to-1.0.md
@@ -32,3 +32,14 @@ siteSubdirName in SiteScaladoc := "jekyll-goodness/api"
 ## Miscellaneous
 In the `PreprocessPlugin`, the key `preprocessExts: SettingKey[Set[String]]` has been replaced by `preprocessIncludeFilter: SettingKey[FileFilter]`.

+`site.addMappingsToSiteDir` no longer exists so if you are using `sbt-unidoc` you need to change:
+
+```scala
+site.addMappingsToSiteDir(mappings in (ScalaUnidoc, packageDoc), "latest/api"),
+```
+
+to the following to have the `sbt-site`'s Scaladoc generator use the files:
+
+```scala
+mappings in (Compile, packageDoc) := (mappings in (ScalaUnidoc, packageDoc)).value
+```
```

**Comment by metasim** [comment]
@jonas I'll take a look at the build issue. Half the time there's a build problem it's a problem with Travis.

Regarding `addMappingsToSiteDir`, there's a pending suggestion from @eed3si9n to think of a more idiomatic sbt way of performing the operation. Rethinking that is the major holdup to releasing 1.0.0, as I'd like the 0.8.2 -> 1.0.0 migration to contain all the breaking changes. If you have any thoughts/opinions on that, it would be appreciated!

**Comment by metasim** [comment]
FWIW, here's where the PR sits:

https://github.com/sbt/sbt-site/tree/release/1.0.0-RC3

Once I get Travis working again, I'll create a binary release.

**Comment by jonas** [comment]
Thanks

**Comment by jonas** [comment]
Regarding build issues, I can look into also locking down the version for the `gitbook-cli` NPM package if you'd like. The `gitbook-cli` is not usually updated that often since all the generators is published separately in the `gitbook` NPM package which can be controlled via GitBooks main config file (the `book.json` file).

**Comment by metasim** [comment]
Pull request has been published to bintray as a part of the 1.0.0-RC3 release.

https://bintray.com/sbt/sbt-plugin-releases/sbt-site/1.0.0-RC3/view

Barring any major problems, should end up in the official 1.0.0 release.

**Comment by jonas** [comment]
Awesome

**Comment by metasim** [comment]
@jonas  Did your updates to the migration document make it in the merge?

**Comment by jonas** [comment]
@metasim No, I only suggested it in the comments. The problem with my suggestion is that it piggybacks on the Scaladoc plugin so it is not very generic. Any reason to not expose `addMappingsToSiteDir` in the site plugin's `autoImport`?

**Comment by metasim** [comment]
@jonas 

I'm going to manually merge it in so as not to forget it, and address the specifics during the 1.0 release.

> Any reason to not expose `addMappingsToSiteDir` in the site plugin's autoImport?

@eed3si9n Had the same suggestion, and it was kinda implemented in #61. However in #60 he suggested changing the function signature to keep keys out of helpers, which I think is good, but I'm at a loss on how to approach it (at least after 5 min thought), to make it worth having at all. Ideally we'd remove the need for it at all, but again, I'm short on ideas ATM.

**Pull request closed without merging**
