### PR TITLE
Publish site

### PR DESCRIPTION
**Pull request by jonas**
- Configure sbt-ghpages for publishing to scala-sbt.org/sbt-site
- Run `make-site` as part of the Travis test
- Enable Travis caching and cleanup `.travis.yml`

The resulting docs are [here](http://www.scala-sbt.org/sbt-site/getting-started.html#publishing).

### CODE REVIEW

**Comment by jonas** [comment]
It looks like the 1.2.0-RC tag is not found on Travis. The docs has `version in Paradox` resolve to 1.1.0.

```sbt
version in Paradox := {
  if (isSnapshot.value) "git tag -l".!!.split("\r?\n").last.substring(1)
  else version.value
}
```

**Comment by jonas** [comment]
Removed the automatic publishing for Travis since there's a more secure way to do this.

**Comment by metasim** [comment]
@jonas Don't hesitate to PM me via Gitter if I'm taking too long to merge PRs. I'm also happy for you to just merge them yourself if you're not needing an extra pair of eyes.

**Comment by jonas** [comment]
@metasim Noted, with Travis config it ended up being less invasive.

BTW, do you think it would be a good idea to set up Travis publishing? It would mostly serve as a showcase, however it requires that somebody with admin rights to the project adds an SSH deploy key to the project.

**Comment by metasim** [comment]
@jonas Just bumped you to admin. I think it's a great idea. Interested in knowing what's involved, generally speaking (i.e. is it just a switch in Travis, or something you add to the `.yml` file

**Comment by jonas** [comment]
OK, thanks. 👍 
Yes, exactly, it uses a deploy step in Travis together with an SSH deploy key.

**Pull request merged**
