### PR TITLE
Gitbook support

### PR DESCRIPTION
**Pull request by jonas**
This adds another site generator. To facilitate building documentation via CI there's a special option to install a local GitBook version for building the site.

### CODE REVIEW

**Comment by jonas** [comment]
OK, third time's a charm. Got it to compile with Java 6 and pass tests once `gitbook` NPM package was installed.

**Comment by metasim** [comment]
@jonas This is a great feature. Do you think you could port it over to the 1.0.0-RCx way of doing things? I hope to get a 1.0 release in the next month, and it would be to have this feature a part of it.

https://github.com/sbt/sbt-site/tree/release/1.0.0-RC2

**Comment by jonas** [comment]
@metasim Yes, definitely, 1.0.0-RC2 looks much improved. I will update the PR.

**Comment by metasim** [comment]
Super! Much appreciated.... and pushes me to make the next release :-)

**Pull request closed without merging**
