### PR TITLE
Add Asciidoctor attribute support

### PR DESCRIPTION
**Pull request by mhogerheijde**
Fixes https://github.com/sbt/sbt-site/issues/156

Allows users to configure `attributes` for Asciidoctor. They are described here: https://asciidoctor.org/docs/user-manual/#attributes

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @mhogerheijde,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by mhogerheijde** [comment]
I have since the initial check accepted the CLA. Is the check repeated automatically?

**Comment by mhogerheijde** [comment]
Can we re-check the CLA?

**Comment by ennru** [comment]
I checked the CLA manually and it's OK.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by mhogerheijde** [comment]
I've included an en-passant update to latest version of AsciidoctorJ.

**Comment by ennru** [comment]
But now the latest commit has a different author, that's why CLA checking fails:
```
Author: Matthias Hogerheijde <matthias.hogerheijde@v**a.com>
Author: Matthias Hogerheijde <matthias.hogerheijde@e**i.nl>
```
Can you squash it and provide the correct author, please.

**Comment by mhogerheijde** [comment]
Ah, that's why.

I'll recommit using my personal git-id. Is there a standard way of doing work in company time and using the git-id from my company with the same Github user-account?

**Comment by mhogerheijde** [comment]
Oh, PEBCAK, just read the CLA stuff again for when it is corporate.

I'll contribute from my personal account :+1:

**Comment by ennru** [comment]
Just came across this, sorry that it kept dangling for so long.

**Pull request merged**
