### PR TITLE
Add support for Hugo static site generator

### PR DESCRIPTION
**Pull request by timperrett**
This PR adds support for the [Hugo](http://gohugo.io/) static site generator (which we find preferable to Jekyll as its a single, static binary, thus avoiding dependency hell with Ruby gems).

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @timperrett,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by timperrett** [comment]
CLA is signed again, although I signed this about 5 years ago before this bot was even alive, on real actual paper :-)

**Comment by djspiewak** [comment]
@timperrett I was wondering about that too…  I'm guessing that the lightbend CLA is distinct from the EPFL CLA.  So if I tried to contribute, I would probably hit a similar error despite signing the CLA.

**Comment by timperrett** [comment]
@djspiewak i actually remember the conversation with Jonas et al for Akka, saying Typesafe (it wasn't called that then) needed a CLA. In a round about way, that bot is probably my fault :-D

**Comment by dwijnand** [comment]
Looks like it's possible to modify $PATH: https://docs.travis-ci.com/user/installing-dependencies/#Installing-Projects-from-Source

.. so we can stay on Docker instances.

**Comment by timperrett** [comment]
@dwijnand yeah i've updated the PR accordingly 👍

**Comment by metasim** [comment]
@timperrett This is looking great! Before merging, could you please update the `README.md`,  file, adding appropriate sections for Hugo, following the established patterns?

**Comment by timperrett** [comment]
@metasim sure, i've updated the README.

**Comment by timperrett** [comment]
@metasim thanks! when will we likely see a release?

**Pull request merged**
