### PR TITLE
Fix Hugo 0.20 version check issue

### PR DESCRIPTION
**Pull request by vshalts**
Hi,

Starting from Hugo 0.20 (current) old regexp used to extract version is broken. I suggest to change version extraction a bit, so it will include all digits up to next non digit symbol. This will fix issue. Probably make sense to fix .travis.yml too to install latest Hugo during testing, but I don't have experience with travis and I haven't touched config file.

### CODE REVIEW

**Comment by jonas** [comment]
Changing the installed version should be a matter of running `s/0.16/0.20/` on the file.

**Comment by vshalts** [comment]
Almost, tgz now absent and tar.gz should be used instead. Added changes for Travis.

**Comment by jonas** [comment]
It looks like they might have changed the packaging. I will take a look later today

**Comment by vshalts** [comment]
Yes, they are. Looks like I fixed it at last. Need to learn how to test Travis locally.

**Comment by jonas** [comment]
Awesome, thanks for also fixing Travis. I usually just copy paste the lines from the file.

**Pull request merged**
